# store

> Store text features to avoid recomputing them.

In [ ]:
#| default_exp store

In [ ]:
#| hide
from nbdev.showdoc import *

In [ ]:
#| export
from __future__ import annotations
from fastcore.basics import patch
import pickle
import os
import hashlib
import sqlite3
import string
import pandas as pd

In [ ]:
#| export
class TextFeatureStore:
	""" A class to store features extracted for a text classification pipeline and cache them to disk to avoid recomputing them. """
	def __init__(self, 
			  	 path:str  # where to save SQLite db to persist the feature store between runs
				 ):
		self.texts = {}
		self.path = path

		if self.path is not None:
			if os.path.dirname(self.path) != '':
				if not os.path.exists(os.path.dirname(self.path)):
					os.makedirs(os.path.dirname(self.path))
		else:
			raise ValueError("The feature store requires a path")

		with sqlite3.connect(self.path) as conn:
			conn.execute('''CREATE TABLE IF NOT EXISTS texts
				(hash TEXT PRIMARY KEY, tokens BLOB NOT NULL, pos BLOB NOT NULL, textstats BLOB NOT NULL) WITHOUT ROWID;''')
			conn.execute('''CREATE TABLE IF NOT EXISTS embeddings
				(hash TEXT PRIMARY KEY, embeddings BLOB NOT NULL) WITHOUT ROWID;''')		
			conn.execute('''CREATE TABLE IF NOT EXISTS lexicons
				(hash TEXT PRIMARY KEY, lexicons BLOB NOT NULL) WITHOUT ROWID;''')	
			conn.commit()

Check out `TokensVectorizer`, `POSVectorizer`, `TextstatsTransformer` and `LexiconCountVectorizer` for examples using a feature store with a Sci-kit learn pipeline.

Initiating a TextFeatureStore creates an SQLite with a texts tables for core features (tokens, parts of speech, textstats, i.e. document-level statistics), an embeddings table for embeddings features, and a lexicons table for lexicon features.

The store is used in a number of Textplumber components. The methods are documented below with examples, but these are primarily as a reference or for implementing new components.

In [ ]:
#| hide
if os.path.exists('feature_store_example.sqlite'):
	os.remove('feature_store_example.sqlite')

In [ ]:
feature_store = TextFeatureStore(path='feature_store_example.sqlite')

In [ ]:
#| export
@patch
def dump(self:TextFeatureStore, 
		 structure_only = False # if True, only show the schema of the feature store
		 ):
	""" Outputs the structure or contents of the feature store (intended for debugging/development) """
	if structure_only == True:
		with sqlite3.connect(feature_store.path) as conn:
			cursor = conn.cursor()
			cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
			tables = cursor.fetchall()
			for table in tables:
				print(table[0])
				cursor.execute(f"PRAGMA table_info({table[0]});")
				columns = cursor.fetchall()
				for column in columns:
					print(column[1:])
				print()
	else:
		with sqlite3.connect(self.path) as conn:
			table = []
			cursor = conn.execute('SELECT * FROM texts')
			for row in cursor:
				dump = {}
				dump['hash'] = row[0]
				dump['tokens'] = pickle.loads(row[1])
				dump['pos'] = pickle.loads(row[2])
				dump['textstats'] = pickle.loads(row[3])
				table.append(dump)

			print(f'Table: texts ({len(table)})')
			if len(table) > 0:
				display(pd.DataFrame(table))

			table = []
			cursor = conn.execute('SELECT * FROM embeddings')
			for row in cursor:
				dump = {}
				dump['hash'] = row[0]
				dump['embeddings'] = pickle.loads(row[1])
				table.append(dump)

			print(f'Table: embeddings ({len(table)})')
			if len(table) > 0:
				display(pd.DataFrame(table))

			table = []
			cursor = conn.execute('SELECT * FROM lexicons')
			for row in cursor:
				dump = {}
				dump['hash'] = row[0]
				dump['lexicons'] = pickle.loads(row[1])
				table.append(dump)

			print(f'Table: lexicons ({len(table)})')
			if len(table) > 0:
				display(pd.DataFrame(table))

Features are retrieved with the hash column. Texts are hashed using MD5. Here is the structure of a store ...

In [ ]:
feature_store.dump(structure_only=True)

texts
('hash', 'TEXT', 1, None, 1)
('tokens', 'BLOB', 1, None, 0)
('pos', 'BLOB', 1, None, 0)
('textstats', 'BLOB', 1, None, 0)

embeddings
('hash', 'TEXT', 1, None, 1)
('embeddings', 'BLOB', 1, None, 0)

lexicons
('hash', 'TEXT', 1, None, 1)
('lexicons', 'BLOB', 1, None, 0)

In [ ]:
#| export
@patch
def update(self:TextFeatureStore, 
			text:str, # the text to update
			tokens:list, # the tokens to update
			pos:list, # the part of speech tags to update
			textstats:list, # the text statistics to update
			):
	"""Update (insert or replce) the feature store with the token, parts of speech tag and textstat (document-level statistics) features for a specific text."""
	hash = hashlib.md5(text.encode()).hexdigest()
	with sqlite3.connect(self.path) as conn:
		conn.execute('''
			INSERT OR REPLACE INTO texts (hash, tokens, pos, textstats)
			VALUES (?, ?, ?, ?)
		''', (hash, pickle.dumps(tokens), pickle.dumps(pos), pickle.dumps(textstats)))
		conn.commit()

In [ ]:
feature_store.update(
		text="This is an example.",
		tokens=["This", "is", "an", "example", "."],
		pos=["DET", "VERB", "DET", "NOUN", "PUNCT"],
		textstats=[1, 3, 5, 7, 9, 11, 1, 3, 5, 7, 9, 11]
)

In [ ]:
feature_store.dump()

Table: texts (1)

,hash,tokens,pos,textstats
0,263fb1aa85489991a2ef832ef10308a0,"[This, is, an, example, .]","[DET, VERB, DET, NOUN, PUNCT]","[1, 3, 5, 7, 9, 11, 1, 3, 5, 7, 9, 11]"

Table: embeddings (0)
Table: lexicons (0)

In [ ]:
#| export
@patch
def update_embeddings(self:TextFeatureStore, 
						texts:str, # the texts to update 
						embeddings:list # the embeddings to update
						):
	"""Update the feature store with embeddings for a list of texts."""

	with sqlite3.connect(self.path) as conn:
		for i, text in enumerate(texts):
			hash = hashlib.md5(text.encode()).hexdigest()
			conn.execute('''
				INSERT OR REPLACE INTO embeddings (hash, embeddings) 
				VALUES (?, ?)
			''', (hash, pickle.dumps(embeddings[i])))
		conn.commit()

In [ ]:
feature_store.update_embeddings(["This is an example."], [[0.1, 0.2, 0.3, 0.4, 0.5]])
feature_store.dump()

Table: texts (1)

,hash,tokens,pos,textstats
0,263fb1aa85489991a2ef832ef10308a0,"[This, is, an, example, .]","[DET, VERB, DET, NOUN, PUNCT]","[1, 3, 5, 7, 9, 11, 1, 3, 5, 7, 9, 11]"

Table: embeddings (1)

                               hash                 embeddings
0  263fb1aa85489991a2ef832ef10308a0  [0.1, 0.2, 0.3, 0.4, 0.5]

Table: lexicons (0)

In [ ]:
#| export
@patch
def update_lexicons(self:TextFeatureStore, 
					texts:str, # the texts to update 
					lexicons:list # the lexicon scores to update
					):
	"""Update the feature store with lexicon features for a list of texts."""

	with sqlite3.connect(self.path) as conn:
		for i, text in enumerate(texts):
			hash = hashlib.md5(text.encode()).hexdigest()
			conn.execute('''
				INSERT OR REPLACE INTO lexicons (hash, lexicons) 
				VALUES (?, ?)
			''', (hash, pickle.dumps(lexicons[i])))
			conn.commit()

In [ ]:
feature_store.update_lexicons(["This is an example."], [[1, 7]])
feature_store.dump()

Table: texts (1)

,hash,tokens,pos,textstats
0,263fb1aa85489991a2ef832ef10308a0,"[This, is, an, example, .]","[DET, VERB, DET, NOUN, PUNCT]","[1, 3, 5, 7, 9, 11, 1, 3, 5, 7, 9, 11]"

Table: embeddings (1)

                               hash                 embeddings
0  263fb1aa85489991a2ef832ef10308a0  [0.1, 0.2, 0.3, 0.4, 0.5]

Table: lexicons (1)

                               hash lexicons
0  263fb1aa85489991a2ef832ef10308a0   [1, 7]

In [ ]:
#| export
@patch
def empty(self:TextFeatureStore):
	"""Clear the contents of the feature store."""
	with sqlite3.connect(self.path) as conn:
		conn.execute('''DELETE FROM texts;''')
		conn.execute('''DELETE FROM embeddings;''')
		conn.execute('''DELETE FROM lexicons;''')
		conn.commit()

In [ ]:
feature_store.empty()
feature_store.dump()

Table: texts (0)
Table: embeddings (0)
Table: lexicons (0)

In [ ]:
#| export
@patch
def buffered_update(self:TextFeatureStore, 
			text:str, # the text to update
			tokens:list, # the tokens to update
			pos:list, # the part of speech tags to update
			textstats:list, # the text statistics to update
			):
	"""Update the feature store tokens, parts of speech tags and text statistics for multiple texts."""
	if not hasattr(self, 'buffer_'):
		self.buffer_ = []
	self.buffer_.append((text, tokens, pos, textstats))
	if len(self.buffer_) > 1000:
		self.flush()

In [ ]:
#| export
@patch
def flush(self:TextFeatureStore):
	"""Flush the buffer to the database."""
	with sqlite3.connect(self.path) as conn:
		for text, tokens, pos, textstats in self.buffer_:
			# hash the text
			hash = hashlib.md5(text.encode()).hexdigest()
			conn.execute('''
				INSERT OR REPLACE INTO texts (hash, tokens, pos, textstats)
				VALUES (?, ?, ?, ?)
			''', (hash, pickle.dumps(tokens), pickle.dumps(pos), pickle.dumps(textstats)))
		conn.commit()
	self.buffer_ = []

In [ ]:
feature_store.buffered_update(
		text="This is an example.",
		tokens=["This", "is", "an", "example", "."],
		pos=["DET", "VERB", "DET", "NOUN", "PUNCT"],
		textstats=[2, 4, 6, 8, 10, 12, 2, 4, 6, 8, 10, 12]
)
print('Updates pending, not flushed ...')
feature_store.dump() # nothing added yet
feature_store.flush() # flush add buffered updates to the store
print()
print('Updates flushed ...')
feature_store.dump() # now the store is updated

Updates pending, not flushed ...
Table: texts (0)
Table: embeddings (0)
Table: lexicons (0)

Updates flushed ...
Table: texts (1)

,hash,tokens,pos,textstats
0,263fb1aa85489991a2ef832ef10308a0,"[This, is, an, example, .]","[DET, VERB, DET, NOUN, PUNCT]","[2, 4, 6, 8, 10, 12, 2, 4, 6, 8, 10, 12]"

Table: embeddings (0)
Table: lexicons (0)

In [ ]:
#| export
@patch
def get(self:TextFeatureStore, 
		text:str, # the text to get features for
		type:str = None # the type of features to get - 'tokens', 'pos', 'textstats', 'embeddings', 'lexicons'
		) -> dict|list: # the features for the text
	""" Get features for a text."""

	if type is not None and type not in ['tokens', 'pos', 'textstats', 'embeddings', 'lexicons']:
		raise ValueError(f"Type {type} not in ['tokens', 'pos', 'textstats', 'embeddings', 'lexicons']")

	with sqlite3.connect(self.path) as conn:
		hash = hashlib.md5(text.encode()).hexdigest()
		if type is None:
			cursor = conn.execute('SELECT * FROM texts WHERE hash=?', (hash,))
			row = cursor.fetchone()
			result = {'tokens': pickle.loads(row[1]), 'pos': pickle.loads(row[2]), 'textstats': pickle.loads(row[3])}
			if row is None:
				return None
			else:
				cursor = conn.execute('SELECT * FROM embeddings WHERE hash=?', (hash,))
				row = cursor.fetchone()
				if row is None:
					result['embeddings'] = None
				else:
					result['embeddings'] = pickle.loads(row[1])

				cursor = conn.execute('SELECT * FROM lexicons WHERE hash=?', (hash,))
				row = cursor.fetchone()
				if row is None:
					result['lexicons'] = None
				else:
					result['lexicons'] = pickle.loads(row[1])
				return result

		elif type in ['tokens', 'pos', 'textstats']:
			cursor = conn.execute(f'SELECT {type} FROM texts WHERE hash=?', (hash,))
			row = cursor.fetchone()
			if row is None:
				return None
			else:
				return pickle.loads(row[0])
		elif type == 'embeddings':
			cursor = conn.execute('SELECT embeddings FROM embeddings WHERE hash=?', (hash,))
			row = cursor.fetchone()
			if row is None:
				return None
			else:
				return pickle.loads(row[0])
		elif type == 'lexicons':
			cursor = conn.execute('SELECT lexicons FROM lexicons WHERE hash=?', (hash,))
			row = cursor.fetchone()
			if row is None:
				return None
			else:
				return pickle.loads(row[0])

The `get` method can return a specific feature type for a text ...

In [ ]:
feature_store.get('This is an example.', type='tokens')

['This', 'is', 'an', 'example', '.']

or all features as a dict ...

In [ ]:
feature_store.get('This is an example.')

{'tokens': ['This', 'is', 'an', 'example', '.'],
 'pos': ['DET', 'VERB', 'DET', 'NOUN', 'PUNCT'],
 'textstats': [2, 4, 6, 8, 10, 12, 2, 4, 6, 8, 10, 12],
 'embeddings': None,
 'lexicons': None}

In [ ]:
#| export
@patch
def get_features_from_texts_by_type(self:TextFeatureStore,
							texts:list, # the texts to get features for
							type:str # the type of features to get - 'tokens', 'pos', 'textstats', 'embeddings', 'lexicons'
							) -> list: # the features for the texts
	""" Get features for a list of texts by type, if no match returns None for the text."""
	hashes = [hashlib.md5(text.encode()).hexdigest() for text in texts]

	if type not in ['tokens', 'pos', 'textstats', 'embeddings', 'lexicons']:
		raise ValueError(f"Type {type} not in ['tokens', 'pos', 'textstats', 'embeddings', 'lexicons']")

	with sqlite3.connect(self.path) as conn:
		if type == 'embeddings':
			cursor = conn.execute(f'SELECT hash, embeddings FROM embeddings WHERE hash IN ({", ".join(["?"] * len(hashes))})', hashes)
		elif type == 'lexicons':
			cursor = conn.execute(f'SELECT hash, lexicons FROM lexicons WHERE hash IN ({", ".join(["?"] * len(hashes))})', hashes)
		else:
			cursor = conn.execute(f'SELECT hash, {type} FROM texts WHERE hash IN ({", ".join(["?"] * len(hashes))})', hashes)
		features = [None] * len(hashes)

		positions = {}
		for i, hash in enumerate(hashes):
			if hash not in positions:
				positions[hash] = []
			positions[hash].append(i)

		for row in cursor:
			if row[0] in hashes:
				for position in positions[row[0]]:
					features[position] = pickle.loads(row[1])
			else:
				raise ValueError(f"Hash {row[0]} not in {hashes}")
		
	return features

Rather than calling `get_features_from_texts_by_type` use the specific method for the feature type ...

In [ ]:
#| export
@patch
def get_tokens_from_texts(self:TextFeatureStore,
							texts:list, # the texts to get tokens for
							lowercase:bool = False, # whether to return tokens as lowercase
							min_token_length:int = 0, # the minimum token length to include
							remove_punctuation:bool = False, # whether to remove punctuation
							remove_numbers:bool = False, # whether to remove numbers
							) -> list: # the tokens for the texts
	""" Get (and optionally filter or transform) tokens for a list of texts. """
	tokens = self.get_features_from_texts_by_type(texts, 'tokens')
	if lowercase == True:
		tokens = [[token.lower() for token in text] if text is not None else None for text in tokens]
	if min_token_length > 0:
		tokens = [[token for token in text if len(token) >= min_token_length] if text is not None else None for text in tokens]
	if remove_punctuation == True:
		tokens = [[token for token in text if token.strip(string.punctuation)] if text is not None else None for text in tokens]
	if remove_numbers == True:
		tokens = [[token for token in text if not token.isdigit()] if text is not None else None for text in tokens]
	return tokens

In [ ]:
feature_store.update(
		text="This is example 2.",
		tokens=["This", "is", "example", "2", "."],
		pos=["DET", "VERB", "NOUN", "NUM", "PUNCT"],
		textstats=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
)

# defaults - if features for a text are not in the store, None is returned
print(feature_store.get_tokens_from_texts(["This is an example.", "This is example 2.", "This is an example that is not in the store."]))
# lowercase
print(feature_store.get_tokens_from_texts(["This is an example.", "This is example 2.", "This is an example that is not in the store."],
                                    lowercase=True))
# min token length
print(feature_store.get_tokens_from_texts(["This is an example.", "This is example 2.", "This is an example that is not in the store."],
									min_token_length=3))
# remove punctuation
print(feature_store.get_tokens_from_texts(["This is an example.", "This is example 2.", "This is an example that is not in the store."],
									remove_punctuation=True))
# remove numbers
print(feature_store.get_tokens_from_texts(["This is an example.", "This is example 2.", "This is an example that is not in the store."],
									remove_numbers=True))

[['This', 'is', 'an', 'example', '.'], ['This', 'is', 'example', '2', '.'], None]
[['this', 'is', 'an', 'example', '.'], ['this', 'is', 'example', '2', '.'], None]
[['This', 'example'], ['This', 'example'], None]
[['This', 'is', 'an', 'example'], ['This', 'is', 'example', '2'], None]
[['This', 'is', 'an', 'example', '.'], ['This', 'is', 'example', '.'], None]

In [ ]:
#| export
@patch
def get_textstats_from_texts(self:TextFeatureStore,
								texts:list, # the texts to get text statistics for
								columns_out = ['tokens_count', 'sentences_count', 'characters_count', 'monosyllabic_words_relfreq', 'polysyllabic_words_relfreq', 'unique_tokens_relfreq', 'average_characters_per_token', 'average_tokens_per_sentence', 'characters_proportion_letters',  'characters_proportion_uppercase', 'hapax_legomena_count', 'hapax_legomena_to_unique'], # the columns to return
								columns_in = ['tokens_count', 'sentences_count', 'characters_count', 'monosyllabic_words_relfreq', 'polysyllabic_words_relfreq', 'unique_tokens_relfreq', 'average_characters_per_token', 'average_tokens_per_sentence', 'characters_proportion_letters',  'characters_proportion_uppercase', 'hapax_legomena_count', 'hapax_legomena_to_unique'], # the possible columns
								) -> list: # the text statistics for the texts
	""" Get document-level text statistics for a list of texts. """
	try:
		columns = [columns_in.index(col) for col in columns_out]
	except ValueError:
		raise ValueError(f"Columns {columns_out} not in {columns_in}")

	textstats = self.get_features_from_texts_by_type(texts, 'textstats')
	textstats = [[textstat[i] for i in columns] if textstat is not None else None for textstat in textstats]
	return textstats

To restrict to specific textstats use `columns_out`. The `columns_in` argument is provided to allow a different definition of available statistics.

In [ ]:
# defaults - if there are no features for a text returns None
print(feature_store.get_textstats_from_texts(["This is an example.", "This is example 2.", "This is an example that is not in the store."]))

# restrict to specific columns - tokens_count, sentence_count ...
print(feature_store.get_textstats_from_texts(["This is an example.", "This is example 2.", "This is an example that is not in the store."],
                                             columns_out = ['tokens_count', 'sentences_count']))

[[2, 4, 6, 8, 10, 12, 2, 4, 6, 8, 10, 12], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], None]
[[2, 4], [1, 2], None]

In [ ]:
#| export
@patch
def get_pos_from_texts(self:TextFeatureStore, 
						texts:list, # the texts to get part of speech tags for
						) -> list: # the part of speech tags for the texts
	""" Get parts of speech for a list of texts. """
	pos = self.get_features_from_texts_by_type(texts, 'pos')
	return pos

In [ ]:
# if there are no features for a text returns None
print(feature_store.get_pos_from_texts(["This is an example.", "This is example 2.", "This is an example that is not in the store."]))

[['DET', 'VERB', 'DET', 'NOUN', 'PUNCT'], ['DET', 'VERB', 'NOUN', 'NUM', 'PUNCT'], None]

In [ ]:
#| export
@patch
def get_embeddings_from_texts(self:TextFeatureStore,
								texts:str # the texts to get embeddings for
								) -> list: # the embeddings for the texts
	""" Get embeddings for multiple texts. """

	embeddings = self.get_features_from_texts_by_type(texts, 'embeddings')
	return embeddings

In [ ]:
feature_store.update_embeddings(["This is an example.", "This is example 2."],[[0.9, -0.5, 3.0, 1.7], [0.5, 0.6, 0.8, -0.9]])

# if there are no features for a text returns None
print(feature_store.get_embeddings_from_texts(["This is an example.", "This is example 2.", "This is an example that is not in the store."]))

[[0.9, -0.5, 3.0, 1.7], [0.5, 0.6, 0.8, -0.9], None]

In [ ]:
#| export
@patch
def get_lexicons_from_texts(self:TextFeatureStore,
							texts:str # the texts to get lexicons for
							) -> list:
	""" Get lexicon features for multiple texts. """
	lexicons = self.get_features_from_texts_by_type(texts, 'lexicons')
	return lexicons

In [ ]:
feature_store.update_embeddings(["This is an example.", "This is example 2."],[[1, 5], [7, 1]])

# if there are no features for a text returns None
print(feature_store.get_embeddings_from_texts(["This is an example.", "This is example 2.", "This is an example that is not in the store."]))

[[1, 5], [7, 1], None]

In [ ]:
#| hide
if os.path.exists('feature_store_example.sqlite'):
	os.remove('feature_store_example.sqlite')

In [ ]:
#| hide
if os.path.exists('test_store.sqlite'):
	os.remove('test_store.sqlite')
text_feature_store = TextFeatureStore('test_store.sqlite')

assert os.path.exists('test_store.sqlite')

text_feature_store.empty()
text_feature_store.update('Hello, world!', ['Hello', 'world'], ['INTJ', 'NOUN'], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

assert text_feature_store.get('Hello, world!') == {'tokens': ['Hello', 'world'], 'pos': ['INTJ', 'NOUN'], 'textstats': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'embeddings': None, 'lexicons': None}
assert text_feature_store.get('Hello, world!', 'tokens') == ['Hello', 'world']
assert text_feature_store.get('Hello, world!', 'pos') == ['INTJ', 'NOUN']
assert text_feature_store.get('Hello, world!', 'textstats') == [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

text_feature_store.update_embeddings(['Hello, world!'], [[1, 2, 3]])
assert text_feature_store.get('Hello, world!', 'embeddings') == [1, 2, 3]

text_feature_store.update_lexicons(['Hello, world!'], [[9, 11, 13]])
assert text_feature_store.get('Hello, world!', 'lexicons') == [9, 11, 13]

text_feature_store.update('Hello, world 123!', ['Hello', 'world', '123'], ['INTJ', 'NOUN'], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
text_feature_store.update('Hello, world 456!', ['Hello', 'world', '456'], ['INTJ', 'NOUN'], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
assert text_feature_store.get_tokens_from_texts(['Hello, world!', 'Hello, world 123!', 'Hello, world 456!']) == [['Hello', 'world'], ['Hello', 'world', '123'], ['Hello', 'world', '456']]

text_feature_store.empty()
assert text_feature_store.get('Hello, world!', 'tokens') is None
assert text_feature_store.get('Hello, world!', 'pos') is None
assert text_feature_store.get('Hello, world!', 'textstats') is None
assert text_feature_store.get_embeddings_from_texts(['Hello, world!']) == [None]
assert text_feature_store.get_lexicons_from_texts(['Hello, world!']) == [None]

text_feature_store.update('Hello, world!', ['Hello', 'world'], ['INTJ', 'NOUN'], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
text_feature_store.update_embeddings(['Hello, world!'], [[1, 2, 3]])
assert text_feature_store.get_embeddings_from_texts(['Hello, world!']) == [[1, 2, 3]]
assert text_feature_store.get_embeddings_from_texts(['Hello, world!', 'Hi, world!']) == [[1, 2, 3], None]

text_feature_store.update_lexicons(['Hello, world!'], [[9, 11, 13]])
assert text_feature_store.get_lexicons_from_texts(['Hello, world!']) == [[9, 11, 13]]
assert text_feature_store.get_lexicons_from_texts(['Hello, world!', 'Hi, world!']) == [[9, 11, 13], None]

text_feature_store.empty()
assert text_feature_store.get('Hello, world!', 'tokens') is None

text_feature_store.update('A Hello, world!', ['A', 'Hello', ',', 'world', '!'], ['INTJ', 'PUNCT', 'NOUN', 'PUNCT'], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
assert text_feature_store.get_tokens_from_texts(['A Hello, world!']) == [['A', 'Hello', ',', 'world', '!']]
assert text_feature_store.get_tokens_from_texts(['A Hello, world!'], lowercase=True) == [['a', 'hello', ',', 'world', '!']]
assert text_feature_store.get_tokens_from_texts(['A Hello, world!'], min_token_length=2) == [['Hello', 'world']]
assert text_feature_store.get_tokens_from_texts(['A Hello, world!'], remove_punctuation=True) == [['A', 'Hello', 'world']]

text_feature_store.empty()
text_feature_store.update('', [], [], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
assert text_feature_store.get('') == {'tokens': [], 'pos': [], 'textstats': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'embeddings': None, 'lexicons': None}

# text_feature_store = TextFeatureStore()
# text_feature_store.update('Hello, world!', ['Hello', 'world'], ['NNP', 'NN'], [1, 1])
# assert text_feature_store.get('Hello, world!') == {'tokens': ['Hello', 'world'], 'pos': ['NNP', 'NN'], 'textstats': [1, 1]}
# text_feature_store.save()
# text_feature_store = text_feature_store.load()
# assert text_feature_store.get('Hello, world!') == {'tokens': ['Hello', 'world'], 'pos': ['NNP', 'NN'], 'textstats': [1, 1]}

text_feature_store.empty()
text_feature_store.update('Hello, world!', ['Hello', 'world'], ['INTJ', 'NOUN'], [1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1])
assert text_feature_store.get_textstats_from_texts(['Hello, world!']) == [[1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1]]
assert text_feature_store.get_textstats_from_texts(['Hello, world!'], columns_out=['tokens_count', 'characters_count']) == [[1, 2]]

# this should raise a value error
try:
    textstats = text_feature_store.get_textstats_from_texts(['Hello, world!'], columns_out=['dr_dre'])
except ValueError as e:
    assert True
else:
    assert False, "Expected ValueError not raised"

del text_feature_store
os.remove('test_store.sqlite')

In [ ]:
#| hide
import nbdev; nbdev.nbdev_export()